<?php
$host = $_SERVER['HTTP_HOST'];
$settings = Yii::$app->settings;
$numberItemPerSiteMap = $settings->get('seo_configuration', 'number_item_per_site_map', 500);
$contents = \cmsbase\modules\PostBase\Post::find()->where(['post_type' => $content_type])->limit($numberItemPerSiteMap)->offset($number*$numberItemPerSiteMap)->all();

$content = <<<XML

XML;

if (!empty($contents)) {
    foreach ($contents as $contentData) {
        $url = \yii\helpers\Url::to(['/post/post/view', 'type' => $content_type, 'slug' => $contentData->slug]);
        $updateTime = $contentData->created_at;
        if ($contentData->updated_at != '0000-00-00 00:00:00') {
            $updateTime = $contentData->updated_at;
        }
        $updateTime = strtotime($updateTime);
        $updateTime = date('Y-m-d\TH:i:s', $updateTime) . '+00:00';
        $content .= <<<XML
<url>
    <loc>http://$host$url</loc>
    <lastmod>$updateTime</lastmod>
</url>

XML;

    }
}
?>
<?= '<?' ?>xml version="1.0" encoding="UTF-8"?><?= '<?' ?>xml-stylesheet type="text/xsl" href="http://<?= $host ?>/assets/main-sitemap.xsl"<?= '?>' ?>
<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd http://www.google.com/schemas/sitemap-image/1.1 http://www.google.com/schemas/sitemap-image/1.1/sitemap-image.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <?= $content ?>
</urlset>
<!-- XML Sitemap generated by TheCatDev SEO -->