<?php

$settings = Yii::$app->settings;
$numberItemPerSiteMap = $settings->get('seo_configuration', 'number_item_per_site_map', 500);
$contentTypes = $settings->get('seo_configuration', 'content_type_in_site_map', []);
if (!empty($contentTypes)) {
    $contentTypes = json_decode($contentTypes);
}
$host = $_SERVER['HTTP_HOST'];
$currentDate = date('Y-m-d\TH:i:s') . '+00:00';
$content = <<<XML
    <sitemap>
        <loc>http://$host/sitemap/main-sitemap.xml</loc>
        <lastmod>$currentDate</lastmod>
    </sitemap>

XML;

foreach ($contentTypes as $contentType) {
    $numberItem = \cmsbase\modules\PostBase\Post::find()->where(['post_type' => $contentType])->count();
    $numberSiteMap = round($numberItem/$numberItemPerSiteMap);
    $numberSiteMap++;
    for ($i = 0; $i < $numberSiteMap; $i++) {
        $content .= <<<XML
    <sitemap>
        <loc>http://$host/sitemap/$contentType-sitemap-$i.xml</loc>
        <lastmod>$currentDate</lastmod>
    </sitemap>

XML;
    }
}

?>
<?= '<?' ?>xml version="1.0" encoding="UTF-8"?><?= '<?' ?>xml-stylesheet type="text/xsl" href="http://<?= $_SERVER['HTTP_HOST'] ?>/assets/main-sitemap.xsl"<?= '?>' ?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <?=$content?>
</sitemapindex>
<!-- XML Sitemap generated by TheCatDev SEO -->