<?php
$host = $_SERVER['HTTP_HOST'];
$content = <<<XML
    <url>
        <loc>http://$host/</loc>
    </url>

XML;

$post_types = get_all_post_type();
foreach ($post_types as $post_type) {
    $url = get_post_type_url($post_type->name);
    $content .= <<<XML
    <url>
        <loc>http://$host$url</loc>
    </url>

XML;
}

?>
<?= '<?' ?>xml version="1.0" encoding="UTF-8"?><?= '<?' ?>xml-stylesheet type="text/xsl" href="http://<?= $host ?>/assets/main-sitemap.xsl"<?= '?>' ?>
<?= '<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd http://www.google.com/schemas/sitemap-image/1.1 http://www.google.com/schemas/sitemap-image/1.1/sitemap-image.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' ?>
    <?= $content ?>
<?= '</urlset>' ?>
<!-- XML Sitemap generated by TheCatDev SEO -->