<?php

Yii::t('app', 'All');
Yii::t('app', 'Page');
Yii::t('app', 'comment');
Yii::t('app', 'Category');
Yii::t('app', 'Tag');
Yii::t('app', 'Product category');
Yii::t('app', 'Product tag');
Yii::t('app', 'Layout');
Yii::t('app', 'Browser');
Yii::t('app', 'Color');
Yii::t('app', 'Retina ready');
Yii::t('app', 'Categories');
Yii::t('app', 'Tags');
Yii::t('app', 'Read More');
Yii::t('app', 'by');
Yii::t('app', 'By');
Yii::t('app', 'Share this article');
Yii::t('app', 'Leave A Reply');
Yii::t('app', 'Submit Now');
Yii::t('app', 'Templates');
Yii::t('app', 'Search your templates');
Yii::t('app', 'website templates from our creative community');
Yii::t('app', 'Low to High');
Yii::t('app', 'High to Low');
Yii::t('app', 'Items per page');
Yii::t('app', 'New');
Yii::t('app', 'Products');
Yii::t('app', 'Popular');
Yii::t('app', 'New Products');
Yii::t('app', 'Popular Products');
Yii::t('app', 'Use It');
Yii::t('app', 'More Info');
Yii::t('app', 'Live Demo');
Yii::t('app', 'Item Details');
Yii::t('app', 'Live Preview');
Yii::t('app', 'Add To Favorites');
Yii::t('app', 'Purchase Now');
Yii::t('app', 'Add To Cart');
Yii::t('app', 'Product Information');
Yii::t('app', 'Product Author');
Yii::t('app', 'Comments');
Yii::t('app', 'Reviews');
Yii::t('app', 'Item FAQ');
Yii::t('app', 'Favorites');
Yii::t('app', 'Released');
Yii::t('app', 'Updated');
Yii::t('app', 'Version');
Yii::t('app', 'Leave a comment');
Yii::t('app', 'Filter Products');
Yii::t('app', 'Signup');
Yii::t('app', 'Weekly Featured Products');
Yii::t('app', 'Newest Release Products');
Yii::t('app', 'Filter by:');
Yii::t('app', 'Trending items');
Yii::t('app', 'Low price');
Yii::t('app', 'High price');
Yii::t('app', 'Best seller');
Yii::t('app', 'All New Products');
Yii::t('app', 'Write your comment...');
Yii::t('app', 'Welcome Back');
Yii::t('app', 'You can sign in with your username');
Yii::t('app', "Don't have an");
Yii::t('app', "account");
Yii::t('app', "Login Now");
Yii::t('app', "Search ...");
Yii::t('app', "Items Per Page");
Yii::t('app', "Per Page ...");
Yii::t('app', "Select ...");
Yii::t('app', "Submit");
Yii::t('app', 'Unlimited');
Yii::t('app', 'Out of stock');
Yii::t('app', 'Are you want to do this?');
Yii::t('app', 'Bulk Actions ...');
Yii::t('app', 'Apply');
Yii::t('app', 'Post comment');
Yii::t('app', 'Product comment');
Yii::t('app', 'Portfolio comment');
Yii::t('app', 'Yes');
Yii::t('app', 'No');
Yii::t('app', 'Input');
Yii::t('app', 'Output');
Yii::t('app', 'In Put');
Yii::t('app', 'Out Put');
Yii::t('app', 'Paid');
Yii::t('app', 'Unpaid');
Yii::t('app', 'Un locked');
Yii::t('app', 'Success');
Yii::t('app', 'Cash');
Yii::t('app', 'Online banking');
Yii::t('app', 'My Orders');
Yii::t('app', 'Processing');
Yii::t('app', 'Transport');
Yii::t('app', 'Fruit');
Yii::t('app', 'Total Order');
Yii::t('app', 'Total Order Price');
Yii::t('app', 'Total Order Discount');
Yii::t('app', 'Total Pending Order Price');
Yii::t('app', 'Total Pending Order Price');
Yii::t('app', 'Security Settings');